UEnquire/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
    path('', include('twitter.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}), 
    
]

chatbot/urls.py
from django.urls import path
from django.urls import reverse
from . import views
import twitter.views

app_name = 'chatbot'

urlpatterns = [
    path("chatbot/<uuid>/", views.chatbot, name='chatbot_chatbot'),
    path("post/<uuid>/", views.chatbot_process, name='post'),
    path("", views.landing, name='home'),

]

twitter/urls.py
from django.urls import path
from . import views
from .views import (intentsDeleteView,sourcesDeleteView,linksDeleteView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'twitter'

urlpatterns = [
    path("dashboard/", views.twitter_data, name = "chatbot-twitter-data"),
    path('train/', views.train_data, name='chatbot_train'),
    path("intents/", views.intents, name = "intents"),
    path("uedata/", views.uedata, name='uedata'),
    path("login/",views.accounts_login, name="login"),
    path('logout/', views.logout_view, name="logout"),

    path("intents/<int:pk>/", intentsDeleteView.as_view(), name="updata_delete"),
    path("twitter/<int:pk>/", sourcesDeleteView.as_view(), name="source_delete"),
    path("links/<int:pk>/", linksDeleteView.as_view(), name="links_delete"),


    path("side/", views.side, name="side"),
    path("Naive_bayes_Trainer/", views.upload, name="upload_file"),

    path("download_excel/", views.download_excel, name="download_excel"),
    path("training_model/", views.train_classifier, name="train_classifier"),


    path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),

    path('links/', views.links, name="links"),
    path('ajax/crud/links/', views.linksViesUTwo.as_view(), name='linksViesUTwo'),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/forms.py
from django import forms
from django.forms import ModelForm
from twitter.models import *

from django.contrib.auth import authenticate
from django.contrib.auth import views
import os


from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import ugettext_lazy as _ 

from django.core.exceptions import ValidationError


class linksForm(ModelForm):
	class Meta:
		model = linksModel
		fields = ['link_name', 'links']

class anaUploadForm(forms.FileField):
	filename = models.CharField(max_length=200)
	json_file = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/pdf'}),)
	class Meta:
		model = analyticsUpload
		fields = '__all__'

class IntentsForm(ModelForm):
	class Meta:
		model = Intents
		fields = ["tag", "pattern", "response", "context", "context_set"]

class SourceForm(ModelForm):
	class Meta:
		model = Source
		fields = ['source_acct']


#ACCOUNT AUTHENTICATION
class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
	class Meta:
		model = Account
		fields = ('username', 'email', 'password1', 'password2',)

	def clean_email(self):

		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Exception as e:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except  Exception as e:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

twitter/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import pandas as pd
from django.contrib.auth.models import User
import os
import random
import json

from tensorflow.keras.models import load_model
# ============================================================
import subprocess
from .models import *
from .forms import *
import re
# ============================================================
from twitter.forms import SourceForm, RegistrationForm, AccountAuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password , check_password
from django.contrib import messages
from twitter.decorators import unauthenticated_user, allowed_users
# ============================================================
from django.views import View
from django.template import loader
# ============================================================
# from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView

from django.core.files.storage import FileSystemStorage

# ========================================================================================
class CrudView(ListView):
    model = Source
    template_name = 'twitter/Crud.html'
    context_object_name = 'source'

class CreateCrudUser(View):
    def  get(self, request):
    	print("<<<<<=================EDIIIITTT========================")
    	name_source = request.GET.get('source_acct', None)
    	print(name_source)
    	obj = Source.objects.create(source_acct = name_source)

    	source = {'twitter_id':obj.twitter_id,'source_acct':obj.source_acct}
    	data = {'source': source}

    	return JsonResponse(data)


class linksViesUTwo(View):
    def  get(self, request):
    	print("<<<<<=================EDIIIITTT========================")
    	link_name = request.GET.get('link_name', None)
    	links = request.GET.get('links', None)
    	obj = linksModel.objects.create(link_name = link_name, links = links)
    	source = {'link_id':obj.link_id,'link_name':link_name, 'links':obj.links}
    	data = {'source': source}
    	return JsonResponse(data)

# ========================================================================================
# UPLOAD DATASET FOR NAIVE BAYES 

from twitter.backend import uploads 
def upload(request):
	files = analyticsUpload.objects.all()
	context = {
		'files': files,
		'classifier_settings': ClassifierSettings.objects.all().last(),
		'model_desc': ClassifierModels.objects.all().last()
	}

	if request.method == 'POST' and 'upload' in request.POST:
		request = uploads.naive_bayes_upload(request, analyticsUpload)

	# Admin inputs
	if request.method == 'POST' and 'new_settings' in request.POST:
		size = request.POST.get('test_size')
		state = request.POST.get('random_state')
		ave = request.POST.get('average')
		entry = ClassifierSettings(test_size=size, rand_state=state, average=ave)
		entry.save()

	return render(request, "twitter/upload_file/analytics_upload.html", context)
# ========================================================================================
# TRAINING OF CLASSIFIER MODEL/ NAIVE BAYES
from twitter.backend import training_classifier as classifier
def train_classifier(request):		
	if request.method == 'POST' and 'train_model' in request.POST:
		file = request.POST.get('train_model')
		file_obj = analyticsUpload.objects.get(name=file)


		# Classifier training(NAIVE BAYES)
		if ClassifierSettings.objects.all().count() != 0:
			settings = ClassifierSettings.objects.all().last()
			model, scores, vectorizer = classifier.naive_bayes(file_obj.file, settings.test_size, settings.rand_state, settings.average)
			entry = ClassifierModels(
				correct=scores['correct'],
				incorrect=scores['incorrect'],
				accuracy=scores['accuracy'],
				recall=scores['recall'],
				precision=scores['precision'],
				f1_score=scores['f1_score']
				)
			entry.save()
		else:
			print("EMPTY CLASSIFIER SETTINGS")
		# sample = ["The University of East has announced suspension.","Corrupted politicians are not hero",
		# "Be sure to vote on the upcomming election", "Signal number 3 sa Bicol", "sd;oosfskfj", 
		# "The Student Council has an important announcement to make this week", 
		# "The UE Journalism has an important integrity to uphold",

		# "university of the east is close for holiday.",
		# "Ester Garcia nag announce ng walang pasok sa buong linggo",
		# "manny paquiao for president!",
		# "urgent just in advisory breaking news"
		# ]
		# matrix = vectorizer.transform(sample)
		# print(model.predict(matrix))
		
	return HttpResponse("CLASSIFIER TRAINING COMPLETE")
# ========================================================================================
# DOWNLOAD TWEETS EXCEL
from twitter.backend import download_file as dl
def download_excel(request):
	request = dl.excel_dl(Tweets)
	return request
# ========================================================================================
# TWITTER MAIN TABLE 
from twitter.backend import tw_backend as tw
@login_required(login_url='twitter:login')
def twitter_data(request):
	api = tw.open_acct()
	num_post = 1
	# Admin Inputs
	if request.method == 'POST' and 'num_posts' in request.POST:
		num_post = int(request.POST.get('number'))

	if request.method == 'POST' and 'sour_sub' in request.POST:
		sources = SourceForm(request.POST)
		if sources.is_valid():
			sources.save()
		else:
			print("Invalid")
	if Source.objects.all().count() == 0:
		accounts = []
	else:
		accounts = Source.objects.all()
		accounts = tw.output(accounts, api, num_post)		
	# CONTEXT
	tweets = Tweets.objects.all()
	context = {'tweets': tweets, 'source_list': accounts}
	return render(request, "twitter/analytics.html", context)
# ========================================================================================
# INTENTS MAIN TABLE
from twitter.backend import intents_backend as intent 
@login_required(login_url='twitter:login')
def intents(request):
	form, data = intent.open_intents(Intents)

	if request.method == 'POST':
		form, new_obj, data, request = intent.request_POST(request, data)	
		with open("twitter/intents.json", 'w') as data_file:
			json.dump(data, data_file, indent=4)
		return JsonResponse({'new_form': new_obj})

	return render(request, "twitter/chatbot_intents.html", {'intents': form})

# class linksViesUTwo(View):
#     def  get(self, request):
#     	print("<<<<<=================EDIIIITTT========================")
#     	link_name = request.GET.get('link_name', None)
#     	links = request.GET.get('links', None)
#     	obj = linksModel.objects.create(link_name = link_name, links = links)
#     	source = {'link_id':obj.link_id,'link_name':link_name, 'links':obj.links}
#     	data = {'source': source}
#     	return JsonResponse(data)
# ========================================================================================
class intentsDeleteView(View):
	
	def get(self,request, pk, *args, **kwargs):
		
		if request.is_ajax():
			print("<<<<<=================DELETE========================")
			tag = Intents.objects.get(pk=pk)
			tag_name = str(tag.tag)
			tag.delete()
			with open("twitter/intents.json", "r") as file:
				data = json.load(file)	

			for item in data["intents"]:
				if item["tag"] == tag_name:
					data["intents"].remove(item)

			with open("twitter/intents.json", 'w') as data_file:
				json.dump(data, data_file, indent=4)

			return JsonResponse({"message":"success"})
		return JsonResponse({"message": "Wrong request"})

class sourcesDeleteView(View):
	def get(self,request, pk, *args, **kwargs):
		if request.is_ajax():
			print("<<<<<=================DELETE========================")
			source = Source.objects.get(pk=pk)
			source.delete()
			return JsonResponse({"message":"success"})
		return JsonResponse({"message": "Wrong request"})

class linksDeleteView(View):
	def get(self,request, pk, *args, **kwargs):
		if request.is_ajax():
			print("<<<<<=================DELETE========================")
			source = linksModel.objects.get(pk=pk)
			source.delete()
			return JsonResponse({"message":"success"})
		return JsonResponse({"message": "Wrong request"})
# ========================================================================================
# TRAINING OF CHATBOT MODEL 
from twitter.backend import training_chatbot as train_bot
def train_data(request):
	train_bot.chatbot_training()
	return render(request, "twitter/train.html", {})

# ========================================================================================
#  WEBSCRAPING THE UE WEBSITE
from twitter.backend import ue_data 
def uedata(request):
	request = ue_data.site(request)
	return HttpResponse("UE DATA UPLOADED SUCCESSFULL")

def get_redirect_if_exists(request):
	redirect = None
	if request.GET:
		if request.GET.get("next"):
			redirect = str(request.GET.get("next"))
	return redirect

# =======================================================================
@unauthenticated_user
def accounts_login(request, *args, **kwargs):
	context = {}
	if request.method=='POST' and 'signUp' in request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			# Account created successfully
			form.save()

			# After registration they are to be logged in
			email = form.cleaned_data.get('email').lower()
			raw_password = form.cleaned_data.get('password1')
			account = authenticate(email=email,password=raw_password)
			login(request,account,backend='django.contrib.auth.backends.ModelBackend')
			
			# san to nakuha??
			destination = kwargs.get("next")
			if destination:
				return redirect(destination)

			messages.info(request, 'Account created successfully')
			return redirect("twitter:login")
		else:
			context['registration_form'] = form

	else:
		form = RegistrationForm()
		context['registration_form'] = form

	
	destination = get_redirect_if_exists(request)

twitter/templates/twitter/analytics.html
{% extends 'twitter/main_admin.html'%}
{% block title %}

Dashboard

{% endblock %}
{% block content %}

<div class="mcw">
  <!--navigation here-->
  <!--main content view-->
  <div class="cv">
    <div>
     <div class="inbox">

       <div class="inbox-bx container-fluid">
<div class="container">
{% if request.user.is_authenticated and request.user.is_staff %}
<h3>UE Twitter Data Analytics using Multinomial Naive Bayes Classification</h3>
	<section>
	<div class="add_source">
	
	
	<!-- ================================================================================= -->
	<!-- Number of Post to college input -->
	<div class="main_s">
<div class="main_s2">
	<div class="ma2">
	SOURCES(Data is multiplied by the number of sources):

		<table id="sourceTable" class="source_table">
			<thead>
				<tr>
					
					<th>Source Name</th>
					<th>Action</th>
				</tr>
				</thead>
				<tbody>
					{% for i in source_list %}
					<tr class="record">
						
						<td>{{i.source_acct}}</td>
						<td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'twitter:source_delete' i.twitter_id %}" class="source_delete btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt del_s"></span></a></p></td>
					</tr>
					{% endfor %}
				</tbody>
		</table>

	<form method="POST" id="addUser">
		{% csrf_token %}
	    <div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">Add Source</span>
			</div>
			<input type="text" name="source_acct" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
			<button type="submit" class="btn btn-primary su" name="sour_sub">Submit</button>
			</div>
	    
	</form>
</div>
	<span class="ma1">
	<form method="POST">
		{% csrf_token %}
			<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">Add Data #:</span>
			</div>
			<input type="text" name="number" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" onkeypress="isInputNumber(event)">
			<input type="submit" class="btn btn-primary su" name="num_posts">
			</div>
	    

	</form>
	</span>

	</div>

	<form method="POST" action="{% url 'twitter:download_excel' %}">
		{% csrf_token %}
		<button type="submit" value="Download EXCEL" name="download">
			Download_EXCEL
        	<span id="pdfButton2" ></span>                                    
        </button>

	</form>
</div>
	</div>
</section>

	<!-- ================================================================================== -->

	<section class="recent">
		<!-- ------------------------ -->
		<div class="activity-card">
			<div id="header-card">
				<h3>UE Official Twitter Page</h3>
			</div>

			<div class="table-responsive">
				<table id="myTable" class="table" >
				
					<thead>
						<tr>
							<th>#</th>
							<th>SOURCE</th>
							<th>POSTS</th>
							<th>LIKES</th>
							<th>DATE CREATED</th>
							<th>TIME CREATED</th>
							<th>HASHTAGS</th>
							<th>LINKS</th>
						</tr>
					</thead>
					<tbody>
						{% for i in tweets %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{i.source}}</td>
							<td>{{i.posts}}</td>
							<td>{{i.likes}}</td>
							<td>{{i.dates}}</td>
							<td>{{i.time}}</td>
							<td>{{i.tags}}</td>
							<td>{{i.links}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>                  
	</section>
	<br>
	= Upload button/ upload form<br>
	* Instruction on the format to upload<br>
	* Dataset Name <br>
	* Daytaset upload input<br>

	= Input to run dataset on naive bayes. 
	*

	{% endif %}

	{% if request.user.is_authenticated and request.user and request.user.is_staff == False  %}
		<p>Sample user</p>
	{% endif %} 
</div>

    </div>
     </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">
	$("form#addUser").submit(function() {
    console.log("GGGGGG")
    var sourceInput = $('input[name="source_acct"]').val().trim();
    if (sourceInput) {
        // Create Ajax Call
        $.ajax({
            url: '{% url "twitter:crud_ajax_create" %}',
            data: {
                'source_acct': sourceInput,
            },
            dataType: 'json',
            success: function (data) {
                
                if (data.source) {
                  
                  appendToUsrTable(data.source);
                }
            }
        });
      } else {
        alert("Please check your input!.");
    }
    $('form#addUser').trigger("reset");
    return false;
});
	
function appendToUsrTable(source) {
	console.log(source.twitter_id)
	let sour = source.twitter_id;
	var url = "{% url 'twitter:source_delete' 123 %}".replace(/123/, sour.toString());

  $("#sourceTable > tbody:last-child").append(`
  	<tr class="record">
  	<td>${source.source_acct}</td>
  	<td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="${url}" class="source_delete2 btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt del_s"></span></a></p></td>
  	<tr>
    `);

  $(".source_delete2").on("click", function(e){
    e.preventDefault();
    console.log("Hi")
    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});
}

	$(".source_delete").on("click", function(e){
    e.preventDefault();
    console.log("Hi")
    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});





</script>
{% endblock scripts %}

twitter/templates/twitter/base_try.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Title{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block stylesheet %}{% endblock stylesheet %}
  </head>
  <body>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
    {% block javascript %}
    {% endblock javascript%}
  </body>
</html>

twitter/templates/twitter/chatbot_intents.html
{% extends 'twitter/main_admin.html'%}
{% block title %}

Chatbot Intents

{% endblock %}
{% block content %}

<div class="mcw">
  <!--navigation here-->
  <!--main content view-->
  <div class="cv">
    <div>
     <div class="inbox">

       <div class="inbox-bx container-fluid">
<div class="container">   
<!-- ======================================================================================= -->
<button type="button" class="btn btn-primary btn_int" data-toggle="modal" data-target="#exampleModalCenter">
  Add new intents
</button>


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add new intents</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" id="new_intents_form" action="">
      	{% csrf_token %}
      <div class="modal-body">
		<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">Tag</span>
			</div>
			<input type="text" name="tag" id="tag" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" required="">
			 <small class="text-red text-muted mySpan"></small>
		</div>


		<div class="form-group">
			<label for="exampleFormControlTextarea1">Patterns:</label>
			<textarea class="form-control" id="pattern"  name="pattern" rows="3" required></textarea>
		</div>
		<div class="form-group" >
			<label for="exampleFormControlTextarea1">Responses:</label>
			<textarea class="form-control" id="response"  name="response" rows="3" required></textarea>
			 
		</div>


	
			<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">Context:</span>
			</div>
			<input type="text" name="context" id="context" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" value=" ">
		</div>
	    
		<div class="form-group" >
			<label for="exampleFormControlTextarea1">Context Set</label>
			<textarea class="form-control" id="context_set"  name="context_set" rows="3" value=" "></textarea>
		</div>
	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" name="submit_add">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
<!-- ======================================================================================= -->


            <section class="recent">
                    <!-- ------------------------ -->
                    <div class="activity-card">
                    <div id="header-card">
                        <h3>DATABASE INTENTS</h3>
                    </div>

                        <div class="table-responsive">
                            <table id="myTable" class="table" >
                                <thead>
                                	<tr>
                                		
                                		<th>#</th>
                                		<th>Tag</th>
                                		<th>Patterns</th>
                                		<th>Responses</th>
                                		<th>Context</th>
                                		<th>Context Set</th>
                                		<th>Delete</th>
                                	</tr>
                                </thead>
                                <tbody>
                                        {% for i in intents %}
                                        <tr class="record">
                                 
                                        	<td>{{ forloop.counter }}</td>
                                        	<td>{{i.tag}}</td>
                                        	<td>{{i.pattern}}</td>
                                        	<td>{{i.response}}</td>
                                        	<td>{{i.context}}</td>
                                        	<td>{{i.context_set}}</td>
    <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'twitter:updata_delete' i.id_tag %}" class="link-delete btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt"></span></a></p></td>
                                        </tr>
                                        {% endfor %}
                                    
                                </tbody>
                            </table>

                        </div>
                    </div>    
            </section>
</div>

    </div>
     </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scripts %}
<!-- REFERENCE LINK -->
<!-- https://www.youtube.com/watch?v=rcbvOVQMjdE&t=109s -->





<!-- ========================================== -->


<script>
	$("#new_intents_form").on("submit", function(e){
	e.preventDefault();
		console.log("Hello")
		
		var url = '{% url "twitter:intents" %}'
		
		$.ajax({
			type:'POST',
			url:url,
			data:{
				tag:$('#tag').val(),
				patterns:$('#pattern').val(),
				responses:$('#response').val(),
				context:$('#context').val(),
				context_set:$('#context_set').val(),
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			success:function(data){
				console.log(data,"<<<")
				$("#exampleModalCenter").modal('hide');
				$('.modal-backdrop').hide();

				alert("Created new intents");
				$('#tag').val('');
				$('#pattern').val('');
				$('#response').val('');
				$('#context').val('');
				$('#context_set').val('');
				window.location = url;
			

			}
		});
	});


// $("#myTable tbody").on("click", ".link-edit", function(e){
// 	e.preventDefault();
// 	var $this = $(this);
// 	let tag = $this.parents(".record").find('td').eq(1).text();
// 	let pattern = $this.parents(".record").find('td').eq(2).text();
// 	let response = $this.parents(".record").find('td').eq(3).text();
// 	let context = $this.parents(".record").find('td').eq(4).text();
// 	let context_set = $this.parents(".record").find('td').eq(5).text();
// 	$("#new_intents_form2 input[name='tag']").val(tag);
// 	$("#new_intents_form2 textarea[name='pattern']").val(pattern);
// 	$("#new_intents_form2 textarea[name='response']").val(response);
// 	$("#new_intents_form2 input[name='context']").val(context);
// 	$("#new_intents_form2 textarea[name='context_set']").val(context_set);
// 	$("#new_intents_form2").attr("action", $this.attr('href'));
// 	$("#exampleModalCenter2").modal("show");
// 	return false;
// });



	$(".link-delete").on("click", function(e){
    e.preventDefault();

    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});



</script>
{% endblock scripts %}

  

twitter/templates/twitter/train.html
<!DOCTYPE html>
<html>
<head>
	<title>Training Data</title>
</head>
<body>
	<h1>Train Data</h1>
</body>
</html>

twitter/templates/twitter/train_classifier.html
<!DOCTYPE html>
<html>
<head>
	<title>Train Classifier</title>
</head>
<body>
	TRAINING COMPLETE 
</body>
</html>